name: Build Arch Linux package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:base-devel
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel rsync
        
    - name: Create build user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
    - name: Build package
      run: |
        chmod -R 777 .
        su builder -c 'cd $GITHUB_WORKSPACE && makepkg -f --noconfirm'
        
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          *.pkg.tar.zst
          *.pkg.tar.xz