name: Build Arch Linux Package

on:
  push:
    branches:
      - main  # Запускати на основній гілці
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Використовуємо контейнер Ubuntu для збірки

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y archlinux-keyring devtools

      - name: Create Arch Linux chroot
        run: |
          sudo mkarchroot /tmp/root base-devel
          sudo cp -r . /tmp/build

      - name: Build package
        run: |
          sudo arch-chroot /tmp/root bash -c "
          cd /tmp/build &&
          makepkg --syncdeps --noconfirm --cleanbuild"

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: "*.pkg.tar.zst"