name: Build Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build in Arch Linux container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:base
          options: --privileged
          run: |
            pacman -Sy --noconfirm base-devel sudo
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            sudo -u builder bash -c "
              cd /github/workspace
              makepkg --syncdeps --noconfirm
            "

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: "*.pkg.tar.zst"